name: lesson_creation
run-name: "${{github.actor}} created lesson ${{github.ref_name}}"

on: 
    create: 

jobs:
    create_lesson:
        runs-on: ubuntu-latest
        if: github.ref_type == 'branch' && startswith(github.ref_name, 'lesson_')
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: main

            - name: Setup bun
              uses: oven-sh/setup-bun@v2 
            
            - name: Validate contributor
              id: validation
              run: bun .github/scripts/validate-contributor.ts 
              continue-on-error: false
              
              env:
                actor: ${{github.actor}}
                CONTRIBUTORS: ${{secrets.CONTRIBUTORS}}

            - name: Update readme
              id: update-readme
              continue-on-error: false
              if: steps.validation.outcome == 'success'
              run: bun .github/scripts/update-readme.ts

              env:
                BRANCH_NAME: ${{github.ref_name}}

            - name: Commit changes
              if: steps.update-readme.outcome == 'success'
              run: |
                git config user.name 'github-actions[bot]'
                git config user.email 'github-actions[bot]@users.noreply.github.com'
                git add README.md
                git commit -m "Successfully updated readme with lesson ${{github.ref_name}}"
                git push origin main

    