name: Lesson Branch Creation
run-name: "${{github.actor}} created lesson ${{github.ref_name}}"

on:
    push:
        branches:
            - "lesson_*"
        paths:
            - "info.txt"

permissions: 
  actions: write
  contents: write

concurrency:
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

jobs:
    get_branch_metadata:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: ${{github.ref}}

            - name: Read info.txt file
              id: read-file
              run: |
                # Define a unique delimiter
                  EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                  
                  # Start the multiline output with the delimiter
                  echo "info_file<<$EOF" >> "$GITHUB_OUTPUT"
                  
                  # Add file contents
                  cat info.txt >> "$GITHUB_OUTPUT"
                  
                  # End with the delimiter
                  echo "$EOF" >> "$GITHUB_OUTPUT"

        outputs:
            branch_metadata: ${{steps.read-file.outputs.info_file}}

    add_lesson:
        runs-on: ubuntu-latest
        needs: get_branch_metadata

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                ref: main

            - name: Append info.txt file
              run: echo ${{needs.get_branch_metadata.outputs.branch_metadata}} >> info.txt

            # # Not needed in production (only for local testing)
            # - name: Install unzip for bun
            #   run: |
            #       apt-get update -y
            #       apt-get install -y unzip

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install packages
              run: bun install  

            - name: Validate contributor
              id: validation
              run: bun .github/scripts/validate-contributor.ts
              continue-on-error: false

              env:
                  actor: ${{github.actor}}
                  CONTRIBUTORS: ${{secrets.CONTRIBUTORS}}

            - name: Update readme
              id: update-readme
              continue-on-error: false
              if: steps.validation.outcome == 'success'
              run: bun .github/scripts/update-readme.ts

              env:
                  BRANCH_NAME: ${{github.ref_name}}

            - name: Commit changes
              if: steps.update-readme.outcome == 'success'
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add README.md
                  git commit -m "Successfully updated readme with lesson ${{github.ref_name}}"
                  git push origin main
