name: Test Lesson update workflow
run-name: ${{github.actor}} testing the lesson update workflow

concurrency: 
    cancel-in-progress: true
    group: ${{github.workflow}}-${{github.ref}}

on: 
    workflow_call: 
    workflow_dispatch: 
    push: 
        branches: 
            - main

jobs:
    test-workflow-scripts:
        runs-on: ubuntu-latest

        env:
            LAST_UPDATED_AT: ${{github.event.head_commit.timestamp}}
            ACTOR: ${{github.actor}}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install dependancies
              run: bun install --frozen-lockfile

            - name: Run workflow tests
              run: bun run test tests/unit/workflows/*.ts
              continue-on-error: false
              env:
                CONTRIBUTORS: ${{secrets.CONTRIBUTORS}}
                BRANCH_NAME: ${{github.ref_name}}
